### ISSUE TITLE
Does it work ?

### ISSUE THREAD

**Issue by Tnze** [JoshuaDoes/go-yggdrasil#1]
When I was trying to Authenticate,  it shows `Error: &{   0 invalid character '<' looking for beginning of value}`.
And then I insert ` fmt.Println(string(body))`in yggdrasilClient.Authenticate(). It look's like printing a html doc
```html <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.

<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: oCZRyfqWbMf0L8lZ_1g25d0yt-k2jxdiqipiRK_gn3bTA_5DB_5vQg==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>```

**Comment by dazoe** [comment]
I ran into this also, turns out it's because minecraft is using cloudfront and they block the default golang http client's user-agent.

**Comment by Tnze** [comment]
Take a look at this: [auth](https://github.com/Tnze/gomcbot/tree/master/authenticate)
I successed by set header Connection: "keep-alive".
`PostRequest.Header.Set("Connection", "keep-alive")`.

**Comment by JoshuaDoes** [comment]
This issue should be fixed now with the pull request made by @dazoe! Feel free to re-open if you encounter any further issues regarding this particular issue.
