### ISSUE TITLE
defer response body close is in the wrong location

### ISSUE THREAD

**Issue by dazoe** [JoshuaDoes/go-yggdrasil#3]
defer response.Body.Close() should be called before ioutil.ReadAll. as it is now if ReadAll returns an error the response.Body.Close() function will never be called

**Comment by JoshuaDoes** [comment]
Feel free to make another pull request with the fix for this! :D

**Comment by JoshuaDoes** [comment]
I'll go ahead and close this for now, but the opportunity is still available for you to submit a PR
